In [1]:
!pip install kaggle

Collecting kaggle
  Downloading kaggle-1.6.14.tar.gz (82 kB)
     ---------------------------------------- 0.0/82.1 kB ? eta -:--:--
     ---- ----------------------------------- 10.2/82.1 kB ? eta -:--:--
     ------------------ ------------------- 41.0/82.1 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 82.1/82.1 kB 659.2 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six>=1.10 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: python-slugify in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (1.26.16)
Requirement already satisfied: bleach in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\asus\anaconda3\lib\site-packages (from bleach->kaggle) (23.1)
Requirement already satisfied: webencodings in c:\users\asus\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\asus\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asus\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\anaconda3\lib\site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Building wheels for collected packages: kaggle
  Building wheel for kaggle (setup.py): started
  Building wheel for kaggle (setup.py): finished with status 'done'
  Created wheel for kaggle: filename=kaggle-1.6.14-py3-none-any.whl size=105134 sha256=be9fdaac7c718d36f37e0f8eda738f997af64098580c497ed9c08f58461de06d
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\ec\d9\04\93be57edf3835182a8e76d8ff87f7e77a0113f473ba3721ee0
Successfully built kaggle
Installing collected packages: kaggle
Successfully installed kaggle-1.6.14

In [2]:
import kaggle

In [3]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\ASUS\Untitled Folder

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 1.74MB/s]
100%|##########| 200k/200k [00:00<00:00, 1.74MB/s]

In [9]:
#EXTRACT FILE FROM ZIP FILE
import zipfile 
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall() 
zip_ref.close()

In [7]:
#READ DATA FROM THE FILE AND HANDLE NULL VALUES
import pandas as pd
df = pd.read_csv('orders.csv', na_values=['Not Available', 'unknown'])
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [8]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [9]:
#fix the names in shipmode where not available, unknown values as nan
df = pd.read_csv('orders.csv', na_values=['Not Available', 'unknown'])
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [10]:
#fix the name of Ship Mode as Ship_Mode
df.rename(columns={'order Id' : 'order_id', 'city' : 'city', 'Ship Mode' : 'Ship_Mode'})

,Order Id,Order Date,Ship_Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [11]:
#for all
df.columns
#convert list ofstring object
df.columns = df.columns.str.lower()

In [12]:
#convert spaces to underscore
df.columns.str.replace(' ','_')
#assigning
df.columns = df.columns.str.replace(' ','_')

In [13]:
df.columns
df.columns.str.replace(' ','_')

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [14]:
#derive new columns discount, sale price and profit
df['list_price']*df['discount_percent']*.01

0        5.2
1       21.9
2        0.5
3       19.2
4        1.0
        ...
9989     1.2
9990     3.6
9991     5.2
9992     0.9
9993     7.2
Length: 9994, dtype: float64

In [15]:
df['discount']= df['list_price']*df['discount_percent']*.01
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2

In [16]:
df['sale_price'] = df['list_price']-df['discount']
df['profit'] = df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [17]:


df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [18]:
#convert oreder date from object data type to datetime
pd.to_datetime(df['order_date'], format="%Y-%m-%d")
df['order_date']=pd.to_datetime(df['order_date'], format="%Y-%m-%d")

In [19]:
#checking dtypes
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [20]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [21]:
#drop cost price , list price and discount percent coulumns
df.drop(columns=['list_price', 'cost_price', 'discount_percent'], inplace = True) #inplace is used to drop in the  dataset only make the change

In [56]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/38/b4/44efe46d5aff497b6009e4755a5e26a99fd8fe2769857dffa21fad941767/mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl.metadata
  Downloading mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl (14.5 MB)
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB 960.0 kB/s eta 0:00:16
   ---------------------------------------- 0.1/14.5 MB 1.7 MB/s eta 0:00:09
    --------------------------------------- 0.2/14.5 MB 1.6 MB/s eta 0:00:09
    --------------------------------------- 0.3/14.5 MB 1.8 MB/s eta 0:00:08
   - -------------------------------------- 0.5/14.5 MB 2.3 MB/s eta 0:00:07
   - -------------------------------------- 0.6/14.5 MB 2.2 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/14.5 MB 2.5 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/14.5 MB 2.3 MB/s eta 0:00:06
   -- ------------------------------------- 1.0/14.5 MB 2.4 MB/s eta 0:00:06
   -- ------------------------------------- 1.0/14.5 MB 2.5 MB/s eta 0:00:06
   -- ------------------------------------- 1.0/14.5 MB 2.5 MB/s eta 0:00:06
   -- ------------------------------------- 1.0/14.5 MB 2.5 MB/s eta 0:00:06
   --- ------------------------------------ 1.1/14.5 MB 1.8 MB/s eta 0:00:08
   --- ------------------------------------ 1.3/14.5 MB 2.0 MB/s eta 0:00:07
   --- ------------------------------------ 1.4/14.5 MB 2.0 MB/s eta 0:00:07
   ---- ----------------------------------- 1.5/14.5 MB 2.1 MB/s eta 0:00:07
   ---- ----------------------------------- 1.6/14.5 MB 2.0 MB/s eta 0:00:07
   ---- ----------------------------------- 1.8/14.5 MB 2.1 MB/s eta 0:00:07
   ----- ---------------------------------- 1.9/14.5 MB 2.2 MB/s eta 0:00:06
   ----- ---------------------------------- 2.0/14.5 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 2.1/14.5 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.2/14.5 MB 2.1 MB/s eta 0:00:06
   ------ --------------------------------- 2.4/14.5 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.5/14.5 MB 2.2 MB/s eta 0:00:06
   ------- -------------------------------- 2.7/14.5 MB 2.3 MB/s eta 0:00:06
   ------- -------------------------------- 2.8/14.5 MB 2.3 MB/s eta 0:00:06
   -------- ------------------------------- 3.0/14.5 MB 2.4 MB/s eta 0:00:05
   -------- ------------------------------- 3.0/14.5 MB 2.4 MB/s eta 0:00:05
   --------- ------------------------------ 3.3/14.5 MB 2.4 MB/s eta 0:00:05
   --------- ------------------------------ 3.3/14.5 MB 2.4 MB/s eta 0:00:05
   --------- ------------------------------ 3.4/14.5 MB 2.3 MB/s eta 0:00:05
   --------- ------------------------------ 3.6/14.5 MB 2.4 MB/s eta 0:00:05
   ---------- ----------------------------- 3.7/14.5 MB 2.4 MB/s eta 0:00:05
   ---------- ----------------------------- 3.9/14.5 MB 2.4 MB/s eta 0:00:05
   ---------- ----------------------------- 3.9/14.5 MB 2.4 MB/s eta 0:00:05
   ----------- ---------------------------- 4.2/14.5 MB 2.5 MB/s eta 0:00:05
   ----------- ---------------------------- 4.3/14.5 MB 2.5 MB/s eta 0:00:05
   ------------ --------------------------- 4.4/14.5 MB 2.5 MB/s eta 0:00:05
   ------------ --------------------------- 4.5/14.5 MB 2.5 MB/s eta 0:00:05
   ------------- -------------------------- 4.7/14.5 MB 2.5 MB/s eta 0:00:04
   ------------- -------------------------- 4.8/14.5 MB 2.5 MB/s eta 0:00:04
   ------------- -------------------------- 5.0/14.5 MB 2.5 MB/s eta 0:00:04
   -------------- ------------------------- 5.1/14.5 MB 2.5 MB/s eta 0:00:04
   -------------- ------------------------- 5.3/14.5 MB 2.6 MB/s eta 0:00:04
   --------------- ------------------------ 5.4/14.5 MB 2.6 MB/s eta 0:00:04
   --------------- ------------------------ 5.6/14.5 MB 2.6 MB/s eta 0:00:04
   --------------- ------------------------ 5.8/14.5 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 5.9/14.5 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 6.0/14.5 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 6.1/14.5 MB 2.6 MB/s eta 0:00:04
   ----------------- ---------------------- 6.1/14.5 MB 2.6 MB/s eta 0:00:04
   ----------------- ---------------------- 6.4/14.5 MB 2.6 MB/s eta 0:00:04
   ----------------- ---------------------- 6.5/14.5 MB 2.6 MB/s eta 0:00:04
   ------------------ --------------------- 6.7/14.5 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 6.7/14.5 MB 2.6 MB/s eta 0:00:03
   ------------------- -------------------- 6.9/14.5 MB 2.6 MB/s eta 0:00:03
   ------------------- -------------------- 7.0/14.5 MB 2.6 MB/s eta 0:00:03
   -------------------- ------------------- 7.2/14.5 MB 2.6 MB/s eta 0:00:03
   -------------------- ------------------- 7.3/14.5 MB 2.6 MB/s eta 0:00:03
   -------------------- ------------------- 7.5/14.5 MB 2.7 MB/s eta 0:00:03
   -------------------- ------------------- 7.5/14.5 MB 2.6 MB/s eta 0:00:03
   --------------------- ------------------ 7.8/14.5 MB 2.7 MB/s eta 0:00:03
   --------------------- ------------------ 7.8/14.5 MB 2.7 MB/s eta 0:00:03
   --------------------- ------------------ 7.8/14.5 MB 2.7 MB/s eta 0:00:03
   --------------------- ------------------ 7.9/14.5 MB 2.6 MB/s eta 0:00:03
   ---------------------- ----------------- 8.0/14.5 MB 2.5 MB/s eta 0:00:03
   ---------------------- ----------------- 8.1/14.5 MB 2.6 MB/s eta 0:00:03
   ---------------------- ----------------- 8.3/14.5 MB 2.6 MB/s eta 0:00:03
   ----------------------- ---------------- 8.4/14.5 MB 2.6 MB/s eta 0:00:03
   ----------------------- ---------------- 8.6/14.5 MB 2.6 MB/s eta 0:00:03
   ----------------------- ---------------- 8.7/14.5 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 8.9/14.5 MB 2.6 MB/s eta 0:00:03
   ------------------------- -------------- 9.1/14.5 MB 2.6 MB/s eta 0:00:03
   ------------------------- -------------- 9.3/14.5 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 9.4/14.5 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 9.6/14.5 MB 2.7 MB/s eta 0:00:02
   -------------------------- ------------- 9.7/14.5 MB 2.7 MB/s eta 0:00:02
   --------------------------- ------------ 9.9/14.5 MB 2.7 MB/s eta 0:00:02
   --------------------------- ------------ 10.0/14.5 MB 2.7 MB/s eta 0:00:02
   ---------------------------- ----------- 10.2/14.5 MB 2.7 MB/s eta 0:00:02
   ---------------------------- ----------- 10.3/14.5 MB 2.7 MB/s eta 0:00:02
   ----------------------------- ---------- 10.5/14.5 MB 2.7 MB/s eta 0:00:02
   ----------------------------- ---------- 10.7/14.5 MB 2.8 MB/s eta 0:00:02
   ----------------------------- ---------- 10.8/14.5 MB 2.8 MB/s eta 0:00:02
   ------------------------------ --------- 11.0/14.5 MB 2.8 MB/s eta 0:00:02
   ------------------------------ --------- 11.1/14.5 MB 2.8 MB/s eta 0:00:02
   ------------------------------- -------- 11.3/14.5 MB 2.9 MB/s eta 0:00:02
   ------------------------------- -------- 11.5/14.5 MB 2.9 MB/s eta 0:00:02
   -------------------------------- ------- 11.7/14.5 MB 2.9 MB/s eta 0:00:01
   -------------------------------- ------- 11.8/14.5 MB 2.9 MB/s eta 0:00:01
   --------------------------------- ------ 12.0/14.5 MB 2.9 MB/s eta 0:00:01
   --------------------------------- ------ 12.0/14.5 MB 2.9 MB/s eta 0:00:01
   --------------------------------- ------ 12.3/14.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 12.3/14.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 12.5/14.5 MB 3.0 MB/s eta 0:00:01
   ---------------------------------- ----- 12.6/14.5 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 12.8/14.5 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 13.0/14.5 MB 3.0 MB/s eta 0:00:01
   ------------------------------------ --- 13.1/14.5 MB 3.0 MB/s eta 0:00:01
   ------------------------------------ --- 13.3/14.5 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 13.5/14.5 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 13.6/14.5 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 13.7/14.5 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 13.9/14.5 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 14.0/14.5 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  14.2/14.5 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  14.3/14.5 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  14.4/14.5 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  14.4/14.5 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 14.5/14.5 MB 3.0 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.4.0

In [3]:
import pandas as pd
from sqlalchemy import create_engine

# MySQL connection details
username = 'sbm'
password = '1234'
host = '127.0.0.1'
port = '3306'
database = 'T1'  # The actual name of your database

# Create the engine with the correct connection string for MySQL
engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}')


# Example DataFrame
""""
df = pd.DataFrame({
    'column1': [1, 2, 3],
    'column2': ['A', 'B', 'C']
})

# Load the DataFrame into the MySQL database
#df.to_sql('table_name', con=engine, if_exists='replace', index=False)

print("Data loaded successfully!")

"""

Data loaded successfully!

In [22]:
conn=engine.connect()
df.to_sql('df_orders', con=conn, index=False, if_exists = 'replace')

9994

In [23]:
df.describe()

,order_id,order_date,postal_code,quantity,discount,sale_price,profit
count,9994.000000,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2022-12-29 10:20:34.820892672,55190.379428,3.789574,8.037953,221.718901,20.529188
min,1.000000,2022-01-01 00:00:00,1040.000000,1.000000,0.000000,0.000000,-5.000000
25%,2499.250000,2022-06-29 00:00:00,23223.000000,2.000000,0.600000,19.200000,-0.400000
50%,4997.500000,2022-12-28 00:00:00,56430.500000,3.000000,1.800000,49.000000,6.000000
75%,7495.750000,2023-07-03 00:00:00,90008.000000,5.000000,7.000000,201.600000,16.700000
max,9994.000000,2023-12-31 00:00:00,99301.000000,14.000000,905.600000,21734.400000,3624.400000
std,2885.163629,NaN,32063.693350,2.225110,22.978004,601.399604,72.514547

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      9994 non-null   int64
 1   order_date    9994 non-null   datetime64[ns]
 2   ship_mode     9988 non-null   object
 3   segment       9994 non-null   object
 4   country       9994 non-null   object
 5   city          9994 non-null   object
 6   state         9994 non-null   object
 7   postal_code   9994 non-null   int64
 8   region        9994 non-null   object
 9   category      9994 non-null   object
 10  sub_category  9994 non-null   object
 11  product_id    9994 non-null   object
 12  quantity      9994 non-null   int64
 13  discount      9994 non-null   float64
 14  sale_price    9994 non-null   float64
 15  profit        9994 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(9)
memory usage: 1.2+ MB